'use strict';

// ── Simulation state ──────────────────────────────────────────────────────────
const SIM = {
  cwd: '/home/rembrandt',
  user: 'rembrandt',
  windowsShell: false,
  winCwd: 'C:\\Windows\\system32',
  hashesOnDisk: false,
  lootExfiltrated: false,
  dirs: new Set(),
  // ── Metasploit state ──────────────────────────────────────────────────────
  msf: false,           // in msfconsole
  msfModule: null,      // active module path
  msfOpts: {},          // set options per module: { [module]: { OPT: val } }
  msfSessions: [],      // active sessions
  msfMeter: false,      // in meterpreter
  msfMeterId: null,     // active session id
  msfMeterWin: false,   // in windows shell from meterpreter
  msfLastSearch: [],    // module names from the last `search` (for `use <n>`)
  legacyPwned: false,   // EternalBlue succeeded
  kiwiLoaded: false,    // mimikatz/kiwi loaded into meterpreter
  lsassDumped: false,   // lsass.dmp written to disk on the target
  persistenceInstalled: false,  // run persistence has been executed
  files: {
    '/home/rembrandt/notes.txt': `# Notes - DO NOT SHARE
# Found on workstation WS01 during initial recon
# ---
john.doe:Password1!
# TODO: rotate these after project ends`,
    '/root/notes.txt': `# Notes - DO NOT SHARE
# Found on workstation WS01 during initial recon
# ---
john.doe:Password1!
# TODO: rotate these after project ends`,
    '/home/rembrandt/.bash_history': `sudo nmap -sn 10.10.10.0/24\nsudo nmap -sV -sC 10.10.10.10\nenum4linux -a 10.10.10.10`,
    '/etc/hosts': `127.0.0.1   localhost\n10.10.10.5  rembrandt\n10.10.10.10 DC01.CORP.LOCAL`,
    '/etc/passwd': `root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nrembrandt:x:1000:1000:Rembrandt,,,:/home/rembrandt:/bin/bash`,
    '/etc/os-release': `PRETTY_NAME="Rembrandt GNU/Linux Rolling"\nNAME="Rembrandt GNU/Linux"\nID=rembrandt\nID_LIKE=debian\nVERSION="2024.2"\nHOME_URL="https://www.rembrandt.org/"`,
    '/etc/hostname': `rembrandt`,
    '/etc/fstab': `/dev/sda1  /          ext4  errors=remount-ro  0  1\n/dev/sda2  none       swap  sw                 0  0\ntmpfs      /tmp       tmpfs defaults,nosuid,nodev 0 0`,
    '/etc/resolv.conf': `# Generated by NetworkManager\nnameserver 10.10.10.1\nnameserver 8.8.8.8\nsearch corp.local`,
    '/etc/crontab': `# /etc/crontab: system-wide crontab\nSHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n\n# m h dom mon dow user  command\n17 *  * * *  root  cd / && run-parts --report /etc/cron.hourly\n25 6  * * *  root  test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )\n47 6  * * 7  root  test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )`,
    '/etc/shadow': `root:!:19736:0:99999:7:::\ndaemon:*:19736:0:99999:7:::\nrembrandt:$6$rounds=656000$randomsalt$hashedpassword:19736:0:99999:7:::`,
    '/etc/group': `root:x:0:\ndaemon:x:1:\nsudo:x:27:rembrandt\nadm:x:4:rembrandt\ncdrom:x:24:rembrandt\ndip:x:30:rembrandt\npluggdev:x:46:rembrandt\nnetdev:x:109:rembrandt\nrembrandt:x:1000:`,
    '/etc/sudoers': `# This file MUST be edited with the 'visudo' command as root.\nDefaults  env_reset\nDefaults  mail_badpass\nDefaults  secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"\n\n# User privilege specification\nroot    ALL=(ALL:ALL) ALL\n\n# Allow members of group sudo to execute any command\n%sudo   ALL=(ALL:ALL) ALL`,
    '/etc/ssh/sshd_config': `# OpenSSH server configuration\nPort 22\nAddressFamily any\nListenAddress 0.0.0.0\nPermitRootLogin no\nPasswordAuthentication yes\nPubkeyAuthentication yes\nAuthorizedKeysFile .ssh/authorized_keys\nX11Forwarding yes\nPrintMotd no\nAcceptEnv LANG LC_*\nSubsystem sftp /usr/lib/openssh/sftp-server`,
    '/etc/motd': `The programs included with the Rembrandt GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Rembrandt GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.`,
    '/etc/issue': `Rembrandt GNU/Linux Rolling \\n \\l`,
    '/etc/shells': `/bin/sh\n/bin/bash\n/usr/bin/bash\n/bin/rbash\n/usr/bin/rbash\n/usr/bin/sh\n/bin/dash\n/usr/bin/dash\n/bin/zsh\n/usr/bin/zsh`,
    '/etc/environment': `PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"`,
    '/etc/login.defs': `MAIL_DIR        /var/mail\nPASS_MAX_DAYS   99999\nPASS_MIN_DAYS   0\nPASS_WARN_AGE   7\nUID_MIN         1000\nUID_MAX         60000\nGID_MIN         1000\nGID_MAX         60000\nCREATE_HOME     yes\nUMASK           022\nUSERGROUPS_ENAB yes\nENCRYPT_METHOD  SHA512`,
    '/tmp/sysinfo.txt': `System: Linux rembrandt 6.6.9-amd64\nUptime: 2:13\nUsers: 1\nLoad: 0.12 0.08 0.05`,
    '/root/root.txt': `THM{r00t_fl4g_d0m41n_4dm1n_0wn3d}`,
    '/root/Documents/loot.txt': `# Domain Loot\nAdministrator:fc525c9683e8fe067095ba2ddc971889\nkrbtgt:9f3a8b2c1d4e5f6a7b8c9d0e1f2a3b4c\nsvc_backup:8c802621d2e36fc074345dded890f3e5`,
    '/root/Downloads/linpeas.sh': `#!/bin/bash\n# linpeas.sh - Linux Privilege Escalation Awesome Script\n# https://github.com/carlospolop/PEASS-ng\necho "[+] Starting LinPEAS..."`,
    '/etc/apt/sources.list': `# Rembrandt Rolling\ndeb http://http.rembrandt.org/rembrandt rembrandt-rolling main contrib non-free non-free-firmware\n# deb-src http://http.rembrandt.org/rembrandt rembrandt-rolling main contrib non-free non-free-firmware`,
    '/proc/version': `Linux version 6.6.9-amd64 (debian-kernel@lists.debian.org) (gcc-13 (Debian 13.2.0-13) 13.2.0, GNU ld (GNU Binutils for Debian) 2.41) #1 SMP PREEMPT_DYNAMIC Rembrandt 6.6.9-1rembrandt1 (2024-01-08)`,
    '/proc/uptime': `8531.42 33124.18`,
    '/proc/loadavg': `0.12 0.08 0.05 1/312 1338`,
    '/proc/meminfo': `MemTotal:        8388608 kB\nMemFree:         4325632 kB\nMemAvailable:    5178208 kB\nBuffers:          213456 kB\nCached:           935472 kB\nSwapTotal:       2097152 kB\nSwapFree:        2097152 kB`,
    '/proc/mounts': `/dev/sda1 / ext4 rw,relatime,errors=remount-ro 0 0\ntmpfs /tmp tmpfs rw,nosuid,nodev 0 0\ntmpfs /run tmpfs rw,nosuid,nodev,noexec,relatime 0 0`,
  },
};

// Random latency helper — adds realistic variance so no two runs feel identical
function jitter(base, spread) {
  return Math.round(base + (Math.random() * 2 - 1) * spread);
}

function simFiles() {
  const home = SIM.user === 'root' ? '/root' : ('/home/' + SIM.user);
  const f = { ...SIM.files };
  if (SIM.hashesOnDisk) {
    f[home + '/hashes.kerberoast'] = KRB5_HASHES;
    f['/home/' + SIM.user + '/hashes.kerberoast'] = KRB5_HASHES;
    f['/root/hashes.kerberoast'] = KRB5_HASHES;
  }
  return f;
}

function isRoot() { return SIM.user === 'root'; }

const KRB5_HASHES = `$krb5tgs$23$*svc_backup$CORP.LOCAL$backup/dc01.corp.local*$8a3f2b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f$1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c
$krb5tgs$23$*svc_sql$CORP.LOCAL$MSSQLSvc/dc01.corp.local:1433*$9b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6$2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e
$krb5tgs$23$*svc_web$CORP.LOCAL$HTTP/web.corp.local*$7c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7$3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f`;

// Handlers — each per-domain file pushes into this array. Order matters: first match wins.
const HANDLERS = [];
